<h2>About this Project</h2>
<p>In this project, you will explore a Jupyter notebook, which you will work with in this and future courses. Below, you will find a series of simple exercises to help introduce you to the functionality of a notebook. There is a pop-out drawer to the right of this window which, when clicked, will reveal a guide that covers the basics of using a Jupyter notebook. This guide will be present in any exercise or project that contains a Jupyter notebook. You will also notice a full screen toggle button in the bottom-right corner of this window.</p>

<h3>Evaluation</h3>

<p><strong>This project must be successfully completed and submitted in order to receive credit for this course. Your score on this project will be included in your final grade calculation.</strong><p>
    
<p>You are expected to write code where you see <em># YOUR CODE HERE</em> within the cells of this notebook. Not all cells will be graded; code input cells followed by cells marked with <em>#Autograder test cell</em> will be graded. Upon submitting your work, the code you write at these designated positions will be assessed using an "autograder" that will run all test cells to assess your code. You will receive feedback from the autograder that will identify any errors in your code. Use this feedback to improve your code if you need to resubmit. Be sure not to change the names of any provided functions, classes, or variables within the existing code cells, as this will interfere with the autograder. Also, remember to execute all code cells sequentially, not just those you’ve edited, to ensure your code runs properly.</p>
    
<p>You can resubmit your work as many times as necessary before the submission deadline. If you experience difficulty or have questions about this exercise, use the Q&A discussion board to engage with your peers or seek assistance from the instructor.<p>

<p>Before starting your work, please review <a href="https://s3.amazonaws.com/ecornell/global/eCornellPlagiarismPolicy.pdf">eCornell's policy regarding plagiarism</a> (the presentation of someone else's work as your own without source credit).</p>

<h3>Submit Code for Autograder Feedback</h3>

<p>Once you have completed your work on this notebook, you will submit your code for autograder review. Follow these steps:</p>

<ol>
  <li><strong>Save your notebook.</strong></li>
  <li><strong>Mark as Completed —</strong> In the blue menu bar along the top of this code exercise window, you’ll see a menu item called <strong>Education</strong>. In the <strong>Education</strong> menu, click <strong>Mark as Completed</strong> to submit your code for autograder/instructor review. This process will take a moment and a progress bar will show you the status of your submission.</li>
	<li><strong>Review your results —</strong> Once your work is marked as complete, the results of the autograder will automatically be presented in a new tab within the code exercise window. You can click on the assessment name in this feedback window to see more details regarding specific feedback/errors in your code submission.</li>
  <li><strong>Repeat, if necessary —</strong> The Jupyter notebook will always remain accessible in the first tabbed window of the exercise. To reattempt the work, you will first need to click <strong>Mark as Uncompleted</strong> in the <strong>Education</strong> menu and then proceed to make edits to the notebook. Once you are ready to resubmit, follow steps one through three. You can repeat this procedure as many times as necessary.</li>
</ol>

<h2>The Structure of Jupyter Notebooks</h2>
    <p>Each body of text or code in a Jupyter notebook is called a cell. A cell has three types: code, markdown, and raw text. </p>

<p>To add a cell, simply select an existing cell (new notebooks are initialized with one), and press the 'a' key to add a new cell above, or the 'b' key to add a new cell below the selected cell. Alternatively, open the <strong>Insert</strong> menu and choose <strong>Insert Cell Below</strong> or <strong>Insert Cell Above</strong>.</p>

<h3>Exercise 1: Add a Cell</h3>

<p>Insert a cell below this one. Change it to a markdown cell by opening the <strong>Cell</strong> menu and selecting <strong>Cell Type > Markdown</strong>. Add some text and then finalize the cell by pressing the shift and enter key or by clicking <strong>Run</strong> in the menu bar at the top of the notebook.</p>


<h2>Running Code</h2>
<p>To execute Python in a cell, the cell type must be set to code. Upon executing a cell (either by pressing shift and enter or clicking <strong>Run</strong> in the menu bar) the output of the code, if any, will appear below the cell containing the code.</p>

<h3>Exercise 2: Cell Type</h3>

<p> Select the cell below and change the type of cell to <strong>code</strong>. Then type a print statement and execute the cell. You should see your print statement output below the cell.</p>


<p> To clear the output, open the <strong>Kernel</strong> menu and select <strong>Restart & Clear Output</strong>. This not only clears all output from executed code, but also restarts the kernel, so any set variables or any other persistent action from previously executed code will be lost. This is because code in subsequent cells share a kernel, which allows you to organize and execute code in a piece-wise manner.</p>

<h2>Autograder Functionality</h2>
<h3>Exercise 3: Simple Expression [Graded]</h3>

<p>Below this markdown cell are four code cells.</p>

<ol>    
<li>The first cell is a read-only cell that you must execute to set the variables. You will <strong>not</strong> be able to edit the content of this cell, though you will need to run it in order to successfully complete the exercise.</li>

<li>In the second cell, you will write some code. Replace "# YOUR CODE HERE" with the expression <code>z = x + y</code>. Remove the line containing the <code>NotImplementedError()</code>.</li>

<li>The third cell contains a self-test that you can run to check and debug your code.</li>

<li>The fourth cell contains an autograde test, which will run when you mark your work as complete and will score your code based on whether it passes or fails the test. The test run in this cell is the exact same test you see in the self-test cell, though the actual test is hidden in the autograde test cell. Each autograde test cell you see in this and subsequent notebooks will contain a single test and will be worth one point.</li>

</ol>
    
<p>Run each cell below, either one at a time (in sequenctial order) or all at once using commands in the <strong>Cell</strong> menu above. You can also press shift and enter to run the currently selected cell.</p>

<p><i>Note that the bracket to the left of each code cell indicates the order in which cells are executed. If cells are not all executed in the correct sequence, it will likely cause your code to fail.</i></p>


Add a Cell as Markdown cell

In [1]:
x = 2
y = 2

In [2]:
# Assign a new variable "z" that is equal to the sum of the expression x + y.

# YOUR CODE HERE
z = x+y

#raise NotImplementedError()

In [3]:
# Run this self-test cell to check your code

assert z == 4, "Your variable z should be equal to x plus y. Try again."

In [4]:
# Autograder test cell - worth 1 Point
# runs test to ensure your expression was written correctly

<h3>Exercise 4: Short Program [Graded]</h3>

<p>In the cell below, write a short program to <code>import numpy as np</code>, initialize a random 3x3 matrix named <code>X</code> using <code>np.random.rand()</code>, and print the matrix. Once you've completed this exercise, don't forget to save your notebook and submit for grading.</p>

In [5]:
# YOUR CODE HERE
import numpy as np
X = np.random.rand(3,3)
print(X)
# raise NotImplementedError()

[[0.02514056 0.40266943 0.87007004]
 [0.87771521 0.30792748 0.63411124]
 [0.85780961 0.88849166 0.30815934]]


In [6]:
# Run this self-test cell to check your code

assert X.shape == (3,3), "Your print statement should output a 3x3 matrix named 'X'."

In [7]:
# Autograder test cell - worth 1 Point
# runs test to ensure your matrix was created properly

<p><strong>Remember to save your notebook before marking your work as complete!</strong></p>